services:
  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    ports:
      - "3001:3001"
    environment:
      - NODE_ENV={process.env.NODE_ENV}
      - PORT={process.env.SERVER_PORT}
      - CLIENT_URL={process.env.CLIENT_URL}
      - DATABASE_URL=${DATABASE_URL}
      - SESSION_SECRET=${SESSION_SECRET}
    depends_on:
      - client
    networks:
      - app-network
    restart: unless-stopped

  client:
    build:
      context: ./client
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV={process.env.NODE_ENV}
      - PORT={process.env.CLIENT_PORT}
      - NEXT_PUBLIC_SERVER_URL={process.env.NEXT_PUBLIC_SERVER_URL}
    networks:
      - app-network
    restart: unless-stopped

networks:
  app-network:
    driver: bridge

volumes:
  app-data:
